<?php

use Illuminate\Database\Seeder;

class PoliticalPartyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table("political_parties")->delete();
        \App\PoliticalParty::insert([
            [
                'id' => 1,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'People Democratic Party',
                'code' => 'PDP',
                'description' => 'The people democratic party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 2,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'All Progressive Congress',
                'code' => 'APC',
                'description' => 'All Progressive Congress',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 3,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'All Progressives Grand Alliance',
                'code' => 'APGA',
                'description' => 'All Progressives Grand Alliance',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 4,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Labour Party',
                'code' => 'LP',
                'description' => 'Labour party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 5,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'New Nigeria People Party',
                'code' => 'NNPP',
                'description' => 'New Nigeria people party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
			[
                'id' => 6,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Accord',
                'code' => 'A',
                'description' => 'Accord',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 7,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Action Alliance',
                'code' => 'AA',
                'description' => 'Action Alliance',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 8,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Advanced Congress Of Democrats',
                'code' => 'ACD',
                'description' => 'Advanced Congress Of Democrats',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 9,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Allied Congress Party of Nigeria',
                'code' => 'ACPN',
                'description' => 'Allied Congress Party of Nigeria',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 10,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Alliance For Democracy',
                'code' => 'AD',
                'description' => 'Alliance For Democracy',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
			[
                'id' => 11,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'African Democratic Congress',
                'code' => 'ADC',
                'description' => 'African Democratic Congress',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 12,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Action Democratic Party',
                'code' => 'ADP',
                'description' => 'Action Democratic Party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 13,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'ALL GRAND ALLIANCE PARTY',
                'code' => 'AGAP',
                'description' => 'ALL GRAND ALLIANCE PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 14,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'African Peoples Alliance',
                'code' => 'APA',
                'description' => 'African Peoples Alliance',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 15,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Advanced Peoples Democratic Alliance',
                'code' => 'APDA',
                'description' => 'Advanced Peoples Democratic Alliance',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 16,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'AFRICAN PEOPLE’S PARTY',
                'code' => 'APP',
                'description' => 'AFRICAN PEOPLE’S PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
			[
                'id' => 17,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'BETTER NIGERIA PROGRESSIVE PARTY',
                'code' => 'BNPP',
                'description' => 'BETTER NIGERIA PROGRESSIVE PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 18,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'DEMOCRATIC ALTERNATIVE',
                'code' => 'DA',
                'description' => 'DEMOCRATIC ALTERNATIVE',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 19,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Democratic Peoples Congress',
                'code' => 'DPC',
                'description' => 'Democratic Peoples Congress',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 20,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Democratic Peoples Party',
                'code' => 'DPP',
                'description' => 'Democratic Peoples Party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 21,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'FRESH DEMOCRATIC PARTY',
                'code' => 'FRESH',
                'description' => 'FRESH DEMOCRATIC PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
			[
                'id' => 22,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Green Party of Nigeria',
                'code' => 'GPN',
                'description' => 'Green Party of Nigeria',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 23,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'HOPE DEMOCRATIC PARTY',
                'code' => 'HDP',
                'description' => 'HOPE DEMOCRATIC PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 24,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'INDEPENDENT DEMOCRATS',
                'code' => 'ID',
                'description' => 'INDEPENDENT DEMOCRATS',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 25,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Kowa Party',
                'code' => 'KP',
                'description' => 'All Progressives Grand Alliance',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 26,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'MASSES MOVEMENT OF NIGERIA',
                'code' => 'MMN',
                'description' => 'MASSES MOVEMENT OF NIGERIA',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 27,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Mega Progressive Peoples Party',
                'code' => 'MPPP',
                'description' => 'Mega Progressive Peoples Party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
			[
                'id' => 28,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'NATIONAL ACTION COUNCIL',
                'code' => 'NAC',
                'description' => 'NATIONAL ACTION COUNCIL',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 29,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'National Conscience Party',
                'code' => 'NCP',
                'description' => 'National Conscience Party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 30,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'NATIONAL DEMOCRATIC LIBERTY PARTY',
                'code' => 'NDLP',
                'description' => 'NATIONAL DEMOCRATIC LIBERTY PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 31,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'NIGERIA ELEMENTS PROGRESSIVE PARTY',
                'code' => 'NEPP',
                'description' => 'NIGERIA ELEMENTS PROGRESSIVE PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 32,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'New Generation Party of Nigeria',
                'code' => 'NGP',
                'description' => 'New Generation Party of Nigeria',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
			[
                'id' => 33,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'NIGERIA PEOPLES CONGRESS',
                'code' => 'NPC',
                'description' => 'NIGERIA PEOPLES CONGRESS',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 34,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'NATIONAL UNITY PARTY',
                'code' => 'NUP',
                'description' => 'NATIONAL UNITY PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 35,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'People For Democratic Change',
                'code' => 'PDC',
                'description' => 'People For Democratic Change',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 36,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Peoples Democratic Movement',
                'code' => 'PDM',
                'description' => 'Peoples Democratic Movement',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 37,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Progressive Peoples Alliance',
                'code' => 'PPA',
                'description' => 'Progressive Peoples Alliance',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 38,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Peoples Party of Nigeria',
                'code' => 'PPA',
                'description' => 'Peoples Party of Nigeria',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
			[
                'id' => 39,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'PEOPLES PROGRESSIVE PARTY',
                'code' => 'PPP',
                'description' => 'PEOPLES PROGRESSIVE PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 40,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'PEOPLES REDEMPTION PARTY',
                'code' => 'PRP',
                'description' => 'PEOPLES REDEMPTION PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 41,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Social Democratic Party',
                'code' => 'SDP',
                'description' => 'Social Democratic Party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 42,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'United Democratic Party',
                'code' => 'UDP',
                'description' => 'United Democratic Party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 43,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Unity Party of Nigeria',
                'code' => 'UPN',
                'description' => 'Unity Party of Nigeria',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
			[
                'id' => 44,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'United Progressive Party',
                'code' => 'UPP',
                'description' => 'United Progressive Party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
            [
                'id' => 45,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'YOUNG DEMOCRATIC PARTY',
                'code' => 'YDP',
                'description' => 'YOUNG DEMOCRATIC PARTY',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ],
			[
                'id' => 46,
                'slug' => bin2hex(random_bytes(64)),
                'name' => 'Young Progressive Party',
                'code' => 'YPP',
                'description' => 'Young Progressive Party',
                'created_at' => '2017-03-09 09:19:28',
                'updated_at' => '2017-03-09 08:19:28',
            ]
        ]);
    }
}
