<?php

use Illuminate\Database\Seeder;

class StateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('states')->truncate();
        DB::table('states')->insert(array(
            'name'=>'Abia'
        ));
        DB::table('states')->insert(array(
            'name'=>'Adamawa'
        ));
        DB::table('states')->insert(array(
            'name'=>'Akwa-Ibom'
        ));
        DB::table('states')->insert(array(
            'name'=>'Anambara'
        ));
        DB::table('states')->insert(array(
            'name'=>'Bauchi'
        ));
        DB::table('states')->insert(array(
            'name'=>'Bayelsa'
        ));
        DB::table('states')->insert(array(
            'name'=>'Benue'
        ));
        DB::table('states')->insert(array(
            'name'=>'Borno'
        ));
        DB::table('states')->insert(array(
            'name'=>'Cross-River'
        ));
        DB::table('states')->insert(array(
            'name'=>'Delta'
        ));
        DB::table('states')->insert(array(
            'name'=>'Ebonyi'
        ));
        DB::table('states')->insert(array(
            'name'=>'Edo'
        ));
        DB::table('states')->insert(array(
            'name'=>'Ekiti'
        ));
        DB::table('states')->insert(array(
            'name'=>'Enugu'
        ));
        DB::table('states')->insert(array(
            'name'=>'Gombe'
        ));
        DB::table('states')->insert(array(
            'name'=>'Imo'
        ));
        DB::table('states')->insert(array(
            'name'=>'Jigawa'
        ));
        DB::table('states')->insert(array(
            'name'=>'Kaduna'
        ));
        DB::table('states')->insert(array(
            'name'=>'Kano'
        ));
        DB::table('states')->insert(array(
            'name'=>'Katsina'
        ));
        DB::table('states')->insert(array(
            'name'=>'Kebbi'
        ));
        DB::table('states')->insert(array(
            'name'=>'Kogi'
        ));
        DB::table('states')->insert(array(
            'name'=>'Kwara'
        ));
        DB::table('states')->insert(array(
            'name'=>'Lagos'
        ));
        DB::table('states')->insert(array(
            'name'=>'Nasarawa'
        ));
        DB::table('states')->insert(array(
            'name'=>'Niger'
        ));
        DB::table('states')->insert(array(
            'name'=>'Ogun'
        ));
        DB::table('states')->insert(array(
            'name'=>'Ondo'
        ));
        DB::table('states')->insert(array(
            'name'=>'Osun'
        ));
        DB::table('states')->insert(array(
            'name'=>'Oyo'
        ));
        DB::table('states')->insert(array(
            'name'=>'Plateau'
        ));
        DB::table('states')->insert(array(
            'name'=>'Rivers'
        ));
        DB::table('states')->insert(array(
            'name'=>'Sokoto'
        ));
        DB::table('states')->insert(array(
            'name'=>'Taraba'
        ));
        DB::table('states')->insert(array(
            'name'=>'Yobe'
        ));
        DB::table('states')->insert(array(
            'name'=>'Zamfara'
        ));
        DB::table('states')->insert(array(
            'name'=>'Federal Capital Territory'
        ));
    }
}
